# ---- JVM ----
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

# ---- AndroidX ----
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# ---- Kotlin ----
kotlin.code.style=official

# 配置缓存：本机（aarch64 Termux）上若出现 AGP 兼容问题，可临时改为 false
org.gradle.configuration-cache=false
